name: Actions-Learn
on: [push]
jobs: 
  SECRET-SSH-ACTIONS: 
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
      with:
        mysecret: ${{ secret.MY_SECRET }}
        script_stop: true
        script: |
          pwd
          ls -l
          touch secret.txt
          echo ${{ secret.MY_SECRET }} >> secret.txt
          